### PR TITLE
Hotel Work in Progress home page created to inform users that more is coming for the page.

### PR DESCRIPTION
**Pull request by davidasteed**
(before this merge:  the changes from "module" branch were merged with this branch)

basic html, sass/scss, red-wall.jpg used for header.   "Site under construction" text added

### CODE REVIEW

**Comment by ZarahZmith** [comment]
The name of the scss files need to be more specific to the actual thing they are doing. In this case mobile should probably be divided into the header and footer. Additionally it would make sense to have the mobile, tablet and desktop views encompassed within the same sass file for organization purposes. The style.css file that is not in the src file should not be committed.

**Comment by BrianFiala** [comment]
I made changes that I believe address the mentioned issues.

**Comment by nmughal** [comment]
Great, looks good. This pull request will add the red-wall image, .DS_Store in the gitignore file, the work in progress html, the style.css file, and three sass files (main, footer, and header).

**Comment by nmughal** [comment]
Great, looks good. This pull request will add the red-wall image, .DS_Store in the gitignore file, the work in progress html, the style.css file, and three sass files (main, footer, and header).

**Pull request merged**
