### PR TITLE
Home page rooms

### PR DESCRIPTION
**Pull request by jakerella**
This PR adds the list of rooms to the home page along with the ability to retrieve them through the controller and service. All rooms are shown currently, but not in any specific order.

NOTE: There are no tests for this ... I'll let my development team do that.

Also note: the build is not correct currently, but this will work once the build process is settled.

### CODE REVIEW

**Comment by jakerella** [comment]
@BrianFiala @nmughal @davidasteed @ZarahZmith Can I get a review from someone?

**Comment by ZarahZmith** [comment]
This looks pretty good just glancing over. The only thing that stands out to me is that we discussed making the "about page" the "home page" with the client until we got the functionality. This seems to resolve that issue as it displays the rooms, but we need to communicate with the client. Unfortunately although the build process was made and merged to the master it does not seem to be working correctly. I think some of the conflicts are related to the build process, but again since that does not seem to be correct I do not feel comfortable resolving those until I know what is critical to the build process versus what may be preventing it from working.

**Comment by jakerella** [comment]
@ZarahZmith Updated the code to reflect latest changes in build process. The home page now appears correct, although there are some unresolved issues with bootstrap and jQuery I can see in the console (nothing to do with this feature though).

As for the client request, if I recall correctly, the client said to put the about stuff there because there was nothing otherwise... sooo, I think it's ok to have this now, and to have a "real" _about _ page.

(FYI, I just pinged the client, he's cool with it.)

**Comment by ZarahZmith** [comment]
Awesome! :shipit:

**Pull request merged**
